"""Extração gratuita por dicionário + regex (sem LLM).

Só encontra o que está nas listas abaixo: amplie TECNOLOGIAS/SOFT conforme
for testando com vagas reais.
"""
import re

TECNOLOGIAS = {
    # --- Linguagens ---
    "JavaScript": ["javascript", "js", "ecmascript", "es6"],
    "TypeScript": ["typescript"],
    "Python": ["python"],
    "Java": ["java"],
    "Kotlin": ["kotlin"],
    "Swift": ["swift"],
    "Objective-C": ["objective-c", "objective c"],
    "C#": ["c#", "c sharp"],
    "C++": ["c++", "cpp"],
    ".NET": [".net", "dotnet", "asp.net", ".net core"],
    "PHP": ["php"],
    "Ruby": ["ruby"],
    "Go": ["golang", "go lang"],
    "Rust": ["rust"],
    "Scala": ["scala"],
    "Dart": ["dart"],
    "Groovy": ["groovy"],
    "Elixir": ["elixir"],
    "Perl": ["perl"],
    "VBA": ["vba"],
    "COBOL": ["cobol"],
    "Delphi": ["delphi"],
    "Bash": ["bash", "shell script", "shell scripting", "shellscript"],
    "PowerShell": ["powershell"],
    # --- Frameworks e bibliotecas ---
    "Node.js": ["node.js", "nodejs", "node"],
    "React": ["react", "reactjs", "react.js"],
    "React Native": ["react native", "react-native"],
    "Angular": ["angular", "angularjs"],
    "Vue": ["vue", "vue.js", "vuejs"],
    "Svelte": ["svelte"],
    "Next.js": ["next.js", "nextjs"],
    "Nuxt": ["nuxt", "nuxt.js"],
    "Redux": ["redux"],
    "jQuery": ["jquery"],
    "Express": ["express.js", "expressjs"],
    "NestJS": ["nestjs", "nest.js"],
    "Spring": ["spring", "spring boot"],
    "Hibernate": ["hibernate"],
    "JPA": ["jpa"],
    "Quarkus": ["quarkus"],
    "Django": ["django"],
    "Flask": ["flask"],
    "FastAPI": ["fastapi"],
    "Laravel": ["laravel"],
    "Symfony": ["symfony"],
    "Rails": ["ruby on rails", "rails"],
    "Blazor": ["blazor"],
    "Entity Framework": ["entity framework", "ef core"],
    "SQLAlchemy": ["sqlalchemy"],
    "Prisma": ["prisma"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy"],
    "TensorFlow": ["tensorflow"],
    "PyTorch": ["pytorch"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    # --- Front-end ---
    "HTML": ["html", "html5"],
    "CSS": ["css", "css3"],
    "Sass": ["sass", "scss"],
    "Tailwind": ["tailwind", "tailwindcss"],
    "Bootstrap": ["bootstrap"],
    "Material UI": ["material ui", "material-ui", "mui"],
    "Webpack": ["webpack"],
    "Vite": ["vite"],
    "Storybook": ["storybook"],
    "Figma": ["figma"],
    "Acessibilidade": ["acessibilidade", "accessibility", "wcag"],
    "PWA": ["pwa", "progressive web app"],
    # --- Mobile ---
    "Android": ["android"],
    "iOS": ["ios"],
    "Flutter": ["flutter"],
    "Jetpack Compose": ["jetpack compose"],
    "SwiftUI": ["swiftui"],
    "Xcode": ["xcode"],
    "Firebase": ["firebase"],
    "Coroutines": ["coroutines", "corrotinas", "corrotina"],
    "Retrofit": ["retrofit"],
    "Expo": ["expo"],
    "Ionic": ["ionic"],
    "Xamarin": ["xamarin"],
    "Kotlin Multiplatform": ["kotlin multiplatform", "kmp"],
    "MVVM": ["mvvm"],
    "Clean Architecture": ["clean architecture", "arquitetura limpa"],
    # --- Bancos de dados e dados ---
    "SQL": ["sql"],
    "PostgreSQL": ["postgresql", "postgres"],
    "MySQL": ["mysql"],
    "SQL Server": ["sql server", "sqlserver", "mssql"],
    "Oracle": ["oracle", "pl/sql"],
    "SQLite": ["sqlite"],
    "MongoDB": ["mongodb"],
    "NoSQL": ["nosql"],
    "Redis": ["redis"],
    "DynamoDB": ["dynamodb"],
    "Elasticsearch": ["elasticsearch", "elastic search"],
    "Cassandra": ["cassandra"],
    "Kafka": ["kafka"],
    "RabbitMQ": ["rabbitmq"],
    "Mensageria": ["mensageria"],
    "Spark": ["spark", "apache spark", "pyspark"],
    "Airflow": ["airflow", "apache airflow"],
    "dbt": ["dbt"],
    "Snowflake": ["snowflake"],
    "BigQuery": ["bigquery"],
    "Databricks": ["databricks"],
    "ETL": ["etl", "elt"],
    "Power BI": ["power bi", "powerbi"],
    "Tableau": ["tableau"],
    "Excel": ["excel"],
    "Machine Learning": ["machine learning", "aprendizado de máquina", "aprendizado de maquina"],
    "LLM": ["llm", "llms", "large language model"],
    "IA generativa": ["ia generativa", "generative ai", "genai"],
    # --- Cloud e infraestrutura ---
    "AWS": ["aws", "amazon web services"],
    "Azure": ["azure"],
    "Google Cloud": ["gcp", "google cloud", "google cloud platform"],
    "Azure DevOps": ["azure devops"],
    "AWS Lambda": ["aws lambda"],
    "Serverless": ["serverless"],
    "Docker": ["docker"],
    "Kubernetes": ["kubernetes", "k8s"],
    "Helm": ["helm"],
    "Terraform": ["terraform"],
    "Ansible": ["ansible"],
    "Linux": ["linux"],
    "Nginx": ["nginx"],
    "DevOps": ["devops"],
    "Prometheus": ["prometheus"],
    "Grafana": ["grafana"],
    "Datadog": ["datadog"],
    "New Relic": ["new relic", "newrelic"],
    "ELK": ["elk", "elastic stack"],
    "Observabilidade": ["observabilidade", "observability"],
    # --- Versionamento e CI/CD ---
    "Git": ["git"],
    "GitHub": ["github"],
    "GitLab": ["gitlab"],
    "Bitbucket": ["bitbucket"],
    "Git Flow": ["git flow", "gitflow"],
    "GitHub Actions": ["github actions"],
    "GitLab CI": ["gitlab ci", "gitlab-ci"],
    "Jenkins": ["jenkins"],
    "ArgoCD": ["argocd", "argo cd"],
    "CI/CD": ["ci/cd", "cicd", "ci-cd"],
    "Maven": ["maven"],
    "Gradle": ["gradle"],
    "SonarQube": ["sonarqube"],
    # --- APIs e arquitetura ---
    "REST": ["restful", "rest api", "apis rest", "api rest", "rest apis", "api restful"],
    "GraphQL": ["graphql"],
    "gRPC": ["grpc"],
    "WebSocket": ["websocket", "websockets"],
    "OAuth": ["oauth", "oauth2", "oauth 2.0"],
    "JWT": ["jwt"],
    "Microsserviços": ["microsserviços", "microsservicos", "microserviços", "microservicos", "microservices"],
    "Clean Code": ["clean code", "código limpo", "codigo limpo"],
    "SOLID": ["princípios solid", "principios solid", "solid principles"],
    "Design Patterns": ["design patterns", "padrões de projeto", "padroes de projeto"],
    "DDD": ["ddd", "domain driven design", "domain-driven design"],
    "POO": ["poo", "programação orientada a objetos", "programacao orientada a objetos", "orientação a objetos", "oop"],
    "Code review": ["code review", "revisão de código", "revisao de codigo"],
    "UML": ["uml"],
    "LGPD": ["lgpd"],
    # --- Testes e qualidade ---
    "Selenium": ["selenium"],
    "Cypress": ["cypress"],
    "Playwright": ["playwright"],
    "Appium": ["appium"],
    "Postman": ["postman"],
    "JUnit": ["junit"],
    "TestNG": ["testng"],
    "Jest": ["jest"],
    "Mocha": ["mocha"],
    "Pytest": ["pytest"],
    "Mockito": ["mockito"],
    "WireMock": ["wiremock"],
    "Cucumber": ["cucumber"],
    "BDD": ["bdd"],
    "TDD": ["tdd"],
    "Robot Framework": ["robot framework"],
    "Rest Assured": ["rest assured", "restassured"],
    "Katalon": ["katalon"],
    "SoapUI": ["soapui", "soap ui"],
    "JMeter": ["jmeter"],
    "K6": ["k6"],
    "Gatling": ["gatling"],
    "LoadRunner": ["loadrunner"],
    "XCUITest": ["xcuitest"],
    "Detox": ["detox"],
    "BrowserStack": ["browserstack"],
    "Sauce Labs": ["sauce labs", "saucelabs"],
    "TestRail": ["testrail"],
    "Xray": ["xray"],
    "Zephyr": ["zephyr"],
    "Allure": ["allure"],
    "Testes automatizados": ["testes automatizados", "automação de testes", "automacao de testes", "test automation", "qa automation"],
    "Testes de API": ["testes de api", "teste de api", "api testing"],
    "Testes de performance": ["testes de performance", "teste de performance", "performance testing", "testes de carga", "teste de carga", "load testing"],
    "Testes de regressão": ["testes de regressão", "teste de regressão", "regression testing"],
    "Testes funcionais": ["testes funcionais", "teste funcional", "functional testing"],
    "Testes manuais": ["testes manuais", "teste manual", "manual testing"],
    "Testes exploratórios": ["testes exploratórios", "teste exploratório", "exploratory testing"],
    "ISTQB": ["istqb", "ctfl"],

        # --- Cibersegurança ---
    "Cybersecurity": ["cybersecurity", "cyber security", "cibersegurança", "ciberseguranca"],
    "Segurança da informação": ["segurança da informação", "seguranca da informacao", "information security", "infosec"],
    "Pentest": ["pentest", "penetration testing", "teste de invasão", "teste de invasao"],
    "Ethical Hacking": ["ethical hacking", "ethical hacker"],
    "SIEM": ["siem"],
    "SOC": ["soc", "security operations center"],
    "Firewall": ["firewall"],
    "OWASP": ["owasp"],
    "ISO 27001": ["iso 27001"],
    "IAM": ["iam", "identity and access management"],
    "Criptografia": ["criptografia", "cryptography"],
    "Vulnerability Management": ["vulnerability management", "gestão de vulnerabilidades", "gestao de vulnerabilidades"],

    # --- Inteligência Artificial ---
    "Inteligência Artificial": ["inteligência artificial", "inteligencia artificial", "artificial intelligence", "ai"],
    "Deep Learning": ["deep learning", "aprendizado profundo"],
    "NLP": ["nlp", "natural language processing", "processamento de linguagem natural"],
    "Computer Vision": ["computer vision", "visão computacional", "visao computacional"],
    "OpenAI": ["openai"],
    "Claude": ["claude", "anthropic"],
    "LangChain": ["langchain"],
    "LlamaIndex": ["llamaindex", "llama index"],
    "RAG": ["rag", "retrieval augmented generation"],
    "Prompt Engineering": ["prompt engineering", "engenharia de prompt"],
    "Fine-tuning": ["fine-tuning", "fine tuning", "ajuste fino"],
    "Hugging Face": ["hugging face", "huggingface"],
    "MLOps": ["mlops"],
    "Modelos de IA": ["modelos de ia", "ai models", "machine learning models"],

    # --- DevOps e infraestrutura ---
    "CI/CD": ["ci/cd", "cicd", "ci-cd"],
    "Infrastructure as Code": ["infrastructure as code", "iac"],
    "Cloud Security": ["cloud security", "segurança em cloud", "seguranca em cloud"],
    "AWS CloudFormation": ["cloudformation", "aws cloudformation"],
    "Pulumi": ["pulumi"],
    "OpenShift": ["openshift"],
    "Istio": ["istio"],
    "Service Mesh": ["service mesh"],

    # --- Dados e Big Data ---
    "Big Data": ["big data"],
    "Data Science": ["data science", "ciência de dados", "ciencia de dados"],
    "Data Engineering": ["data engineering", "engenharia de dados"],
    "Data Analytics": ["data analytics", "análise de dados", "analise de dados"],
    "Data Warehouse": ["data warehouse", "data warehousing"],
    "Data Lake": ["data lake"],
    "Data Lakehouse": ["data lakehouse", "lakehouse"],
    "Apache Flink": ["apache flink", "flink"],
    "Apache Kafka": ["apache kafka", "kafka"],
    "Apache Hadoop": ["apache hadoop", "hadoop"],
    "Apache Hive": ["apache hive", "hive"],
    "Databricks": ["databricks"],
    "dbt": ["dbt"],

    # --- Desenvolvimento de software ---
    "Micro Frontends": ["micro frontends", "micro-frontends"],
    "Arquitetura de Software": ["arquitetura de software", "software architecture"],
    "Arquitetura Hexagonal": ["arquitetura hexagonal", "hexagonal architecture"],
    "Event-Driven Architecture": ["event-driven architecture", "arquitetura orientada a eventos"],
    "Domain-Driven Design": ["domain-driven design", "domain driven design"],
    "SOLID": ["solid", "solid principles"],
    "TypeScript": ["typescript"],
    "WebAssembly": ["webassembly", "wasm"],

    # --- Blockchain e Web3 ---
    "Blockchain": ["blockchain"],
    "Web3": ["web3", "web 3.0"],
    "Smart Contracts": ["smart contracts", "contratos inteligentes"],
    "Ethereum": ["ethereum"],
    "Solidity": ["solidity"],

    # --- IoT e sistemas embarcados ---
    "IoT": ["iot", "internet of things", "internet das coisas"],
    "Arduino": ["arduino"],
    "Raspberry Pi": ["raspberry pi"],
    "Sistemas embarcados": ["sistemas embarcados", "embedded systems"],
    "MQTT": ["mqtt"],
    # --- Gestão e metodologia ---
    "Jira": ["jira"],
    "Confluence": ["confluence"],
    "Trello": ["trello"],
    "Scrum": ["scrum"],
    "Kanban": ["kanban"],
    "Metodologias ágeis": ["agile", "ágil", "agil", "ageis", "ágeis", "metodologia ágil"],
    # --- Linguagens (extras) ---
    "Haskell": ["haskell"],
    "Clojure": ["clojure"],
    "Erlang": ["erlang"],
    "F#": ["f#", "f sharp"],
    "Visual Basic": ["visual basic", "vb.net", "vb6"],
    "Lua": ["lua"],
    "MATLAB": ["matlab"],
    "Fortran": ["fortran"],
    "ABAP": ["abap"],
    "VHDL": ["vhdl"],
    "Verilog": ["verilog"],
    "Mainframe": ["mainframe", "jcl", "as/400", "as400"],

    # --- Frameworks e bibliotecas (extras) ---
    "Fastify": ["fastify"],
    "Koa": ["koa", "koa.js"],
    "AdonisJS": ["adonisjs", "adonis.js"],
    "Gatsby": ["gatsby", "gatsbyjs"],
    "SolidJS": ["solidjs", "solid.js"],
    "HTMX": ["htmx"],
    "Alpine.js": ["alpine.js", "alpinejs"],
    "Three.js": ["three.js", "threejs"],
    "D3.js": ["d3.js", "d3js"],
    "RxJS": ["rxjs"],
    "Zustand": ["zustand"],
    "MobX": ["mobx"],
    "React Query": ["react query", "react-query", "tanstack query"],
    "React Testing Library": ["react testing library", "testing library"],
    "Axios": ["axios"],
    "Zod": ["zod"],
    "tRPC": ["trpc"],
    "Electron": ["electron.js", "electronjs"],
    "Tauri": ["tauri"],
    "Micronaut": ["micronaut"],
    "Vert.x": ["vert.x", "vertx"],
    "Jakarta EE": ["jakarta ee", "java ee", "j2ee"],
    "JSF": ["jsf", "javaserver faces"],
    "Thymeleaf": ["thymeleaf"],
    "Lombok": ["lombok"],
    "MapStruct": ["mapstruct"],
    "Celery": ["celery"],
    "Pydantic": ["pydantic"],
    "Streamlit": ["streamlit"],
    "Scrapy": ["scrapy"],
    "Beautiful Soup": ["beautifulsoup", "beautiful soup", "bs4"],
    "CodeIgniter": ["codeigniter"],
    "WordPress": ["wordpress"],
    "Drupal": ["drupal"],
    "Magento": ["magento"],
    "Shopify": ["shopify"],
    "VTEX": ["vtex"],
    "WPF": ["wpf"],
    "WinForms": ["winforms", "windows forms"],
    ".NET MAUI": [".net maui", "maui"],
    "Unity": ["unity3d", "unity 3d", "unity engine"],
    "Unreal Engine": ["unreal engine", "unreal"],
    "Godot": ["godot"],
    "OpenGL": ["opengl"],
    "OpenCV": ["opencv"],

    # --- Front-end e design (extras) ---
    "Chakra UI": ["chakra ui", "chakra-ui"],
    "Ant Design": ["ant design", "antd"],
    "Styled Components": ["styled-components", "styled components"],
    "shadcn/ui": ["shadcn", "shadcn/ui"],
    "Design System": ["design system", "design systems"],
    "UX/UI": ["ux", "ux/ui", "ui/ux", "ux design", "ui design", "user experience"],
    "Adobe XD": ["adobe xd"],
    "Photoshop": ["photoshop"],
    "Design responsivo": ["design responsivo", "responsive design", "layout responsivo", "mobile first", "mobile-first"],
    "SEO": ["seo"],
    "Core Web Vitals": ["core web vitals", "lighthouse"],
    "SSR": ["ssr", "server-side rendering", "server side rendering"],
    "Web Components": ["web components"],
    "Babel": ["babel"],
    "ESLint": ["eslint"],
    "Prettier": ["prettier"],
    "npm": ["npm"],
    "Yarn": ["yarn"],
    "pnpm": ["pnpm"],
    "Monorepo": ["monorepo", "turborepo"],
    "AJAX": ["ajax"],
    "JSON": ["json"],
    "XML": ["xml"],
    "SOAP": ["soap", "wsdl"],

    # --- Mobile (extras) ---
    "Desenvolvimento mobile": ["desenvolvimento mobile", "mobile development", "mobile developer", "aplicativos mobile", "apps mobile"],
    "Android Jetpack": ["android jetpack"],
    "Material Design": ["material design"],
    "UIKit": ["uikit"],
    "Core Data": ["core data", "coredata"],
    "Alamofire": ["alamofire"],
    "RxSwift": ["rxswift"],
    "RxJava": ["rxjava"],
    "Ktor": ["ktor"],
    "Koin": ["koin"],
    "Dagger Hilt": ["dagger hilt", "dagger/hilt", "hilt"],
    "Riverpod": ["riverpod"],
    "BLoC": ["flutter bloc", "bloc pattern"],
    "CocoaPods": ["cocoapods"],
    "Swift Package Manager": ["swift package manager"],
    "Fastlane": ["fastlane"],
    "Crashlytics": ["crashlytics"],
    "Push Notifications": ["push notifications", "notificações push", "notificacoes push"],
    "Deep Link": ["deep link", "deep links", "deeplink", "deeplinks", "deep linking"],
    "Google Play": ["google play", "play store", "play console"],
    "App Store": ["app store", "app store connect", "testflight"],

    # --- Bancos de dados e dados (extras) ---
    "MariaDB": ["mariadb"],
    "Neo4j": ["neo4j"],
    "CouchDB": ["couchdb"],
    "Couchbase": ["couchbase"],
    "InfluxDB": ["influxdb"],
    "TimescaleDB": ["timescaledb"],
    "ClickHouse": ["clickhouse"],
    "CockroachDB": ["cockroachdb"],
    "Supabase": ["supabase"],
    "Cosmos DB": ["cosmos db", "cosmosdb"],
    "Amazon RDS": ["rds", "amazon rds"],
    "Redshift": ["redshift"],
    "Banco vetorial": ["vector database", "vector db", "banco vetorial", "banco de dados vetorial", "pgvector", "pinecone", "weaviate", "qdrant"],
    "T-SQL": ["t-sql", "tsql", "transact-sql"],
    "PL/pgSQL": ["pl/pgsql", "plpgsql"],
    "Stored Procedures": ["stored procedure", "stored procedures"],
    "Modelagem de dados": ["modelagem de dados", "data modeling"],
    "ORM": ["orm"],
    "TypeORM": ["typeorm"],
    "Sequelize": ["sequelize"],
    "Mongoose": ["mongoose"],
    "Dapper": ["dapper"],
    "Liquibase": ["liquibase"],
    "Flyway": ["flyway"],
    "Alembic": ["alembic"],
    "Debezium": ["debezium"],
    "CDC": ["cdc", "change data capture"],
    "Apache NiFi": ["nifi", "apache nifi"],
    "Apache Beam": ["apache beam"],
    "Delta Lake": ["delta lake"],
    "Dagster": ["dagster"],
    "Prefect": ["prefect"],
    "SSIS": ["ssis"],
    "SSRS": ["ssrs"],
    "SSAS": ["ssas"],
    "Power Query": ["power query"],
    "DAX": ["dax"],
    "Power Apps": ["power apps", "powerapps"],
    "Power Automate": ["power automate"],
    "Looker": ["looker", "looker studio", "data studio"],
    "Qlik": ["qlik", "qlikview", "qlik sense"],
    "Metabase": ["metabase"],
    "Business Intelligence": ["business intelligence", "bi tools", "ferramentas de bi"],
    "Google Sheets": ["google sheets", "google planilhas"],
    "Apps Script": ["apps script"],
    "Qualidade de dados": ["data quality", "qualidade de dados", "great expectations"],
    "Governança de dados": ["data governance", "governança de dados", "governanca de dados"],
    "Estatística": ["estatística", "estatistica", "statistics"],
    "Séries temporais": ["séries temporais", "series temporais", "time series"],
    "Teste A/B": ["teste a/b", "testes a/b", "a/b test", "a/b testing"],
    "Matplotlib": ["matplotlib"],
    "Jupyter": ["jupyter", "jupyter notebook"],
    "Polars": ["polars"],
    "GIS": ["gis", "geoprocessamento", "qgis", "arcgis", "postgis"],

    # --- IA (extras) ---
    "Redes neurais": ["redes neurais", "rede neural", "neural networks"],
    "Transformers": ["transformers", "arquitetura transformer"],
    "Reinforcement Learning": ["reinforcement learning", "aprendizado por reforço", "aprendizado por reforco"],
    "Sistemas de recomendação": ["sistemas de recomendação", "sistemas de recomendacao", "recommender systems", "recommendation systems"],
    "Modelagem preditiva": ["modelagem preditiva", "predictive modeling", "predictive analytics"],
    "Séries de IA: OCR": ["ocr"],
    "Chatbots": ["chatbot", "chatbots", "assistente virtual", "assistentes virtuais", "dialogflow"],
    "GPT": ["gpt", "chatgpt"],
    "Gemini": ["gemini"],
    "Llama": ["llama"],
    "Mistral": ["mistral"],
    "Copilot": ["copilot", "github copilot"],
    "Embeddings": ["embeddings", "embedding"],
    "Agentes de IA": ["ai agents", "agentes de ia", "agentic", "multi-agent", "multiagente"],
    "MCP": ["mcp", "model context protocol"],
    "LangGraph": ["langgraph"],
    "CrewAI": ["crewai"],
    "AutoGen": ["autogen"],
    "Ollama": ["ollama"],
    "vLLM": ["vllm"],
    "Keras": ["keras"],
    "XGBoost": ["xgboost"],
    "MLflow": ["mlflow"],
    "Kubeflow": ["kubeflow"],
    "SageMaker": ["sagemaker"],
    "Vertex AI": ["vertex ai"],
    "Azure OpenAI": ["azure openai"],
    "IA responsável": ["responsible ai", "ia responsável", "ia responsavel", "ética em ia", "etica em ia", "ai ethics"],

    # --- Cloud (extras) ---
    "Amazon EC2": ["ec2", "amazon ec2"],
    "Amazon S3": ["s3", "amazon s3"],
    "Amazon ECS": ["ecs", "amazon ecs", "fargate"],
    "Amazon EKS": ["eks", "amazon eks"],
    "Amazon SQS/SNS": ["sqs", "sns"],
    "Amazon CloudFront": ["cloudfront"],
    "CloudWatch": ["cloudwatch"],
    "API Gateway": ["api gateway"],
    "Step Functions": ["step functions"],
    "Cognito": ["cognito"],
    "AWS CDK": ["aws cdk"],
    "VPC": ["vpc"],
    "Azure Functions": ["azure functions"],
    "AKS": ["aks", "azure kubernetes service"],
    "Azure Data Factory": ["azure data factory", "data factory"],
    "Azure Service Bus": ["azure service bus", "service bus"],
    "Entra ID": ["entra id", "azure ad", "azure active directory"],
    "Cloud Run": ["cloud run"],
    "GKE": ["gke"],
    "Pub/Sub": ["pub/sub", "pubsub"],
    "Oracle Cloud": ["oracle cloud", "oci"],
    "Cloudflare": ["cloudflare"],
    "Vercel": ["vercel"],
    "Netlify": ["netlify"],
    "Heroku": ["heroku"],
    "DigitalOcean": ["digitalocean", "digital ocean"],
    "Multicloud": ["multicloud", "multi-cloud", "multi cloud"],
    "Cloud Computing": ["cloud computing", "computação em nuvem", "computacao em nuvem"],

    # --- DevOps, infraestrutura e redes (extras) ---
    "Docker Compose": ["docker compose", "docker-compose"],
    "Podman": ["podman"],
    "Containers": ["containers", "contêineres", "conteineres", "containerização", "containerizacao"],
    "Rancher": ["rancher"],
    "Kustomize": ["kustomize"],
    "Terragrunt": ["terragrunt"],
    "Vagrant": ["vagrant"],
    "Puppet": ["puppet"],
    "HashiCorp Vault": ["hashicorp vault"],
    "GitOps": ["gitops"],
    "Platform Engineering": ["platform engineering", "engenharia de plataforma"],
    "SRE": ["sre", "site reliability"],
    "FinOps": ["finops"],
    "CircleCI": ["circleci"],
    "TeamCity": ["teamcity"],
    "Travis CI": ["travis ci", "travisci"],
    "Artifactory": ["artifactory", "jfrog"],
    "Nexus": ["sonatype nexus", "nexus repository"],
    "Traefik": ["traefik"],
    "HAProxy": ["haproxy"],
    "Tomcat": ["tomcat"],
    "WildFly": ["wildfly", "jboss"],
    "IIS": ["iis"],
    "Windows Server": ["windows server"],
    "Active Directory": ["active directory"],
    "VMware": ["vmware", "vsphere"],
    "Hyper-V": ["hyper-v", "hyperv"],
    "TCP/IP": ["tcp/ip"],
    "DNS": ["dns"],
    "VPN": ["vpn"],
    "CDN": ["cdn"],
    "Load Balancer": ["load balancer", "balanceador de carga", "balanceamento de carga"],
    "Redes de computadores": ["redes de computadores", "networking", "cisco", "ccna", "ccnp"],
    "Zabbix": ["zabbix"],
    "Nagios": ["nagios"],
    "OpenTelemetry": ["opentelemetry", "otel"],
    "Jaeger": ["jaeger"],
    "Splunk": ["splunk"],
    "Sentry": ["sentry"],
    "Logstash": ["logstash"],
    "Kibana": ["kibana"],

    # --- Segurança (extras) ---
    "DevSecOps": ["devsecops"],
    "SAST/DAST": ["sast", "dast"],
    "AppSec": ["appsec", "application security", "segurança de aplicações", "seguranca de aplicacoes"],
    "Burp Suite": ["burp suite", "burpsuite"],
    "Metasploit": ["metasploit"],
    "Nmap": ["nmap"],
    "Wireshark": ["wireshark"],
    "Kali Linux": ["kali linux"],
    "Nessus": ["nessus"],
    "Qualys": ["qualys"],
    "CrowdStrike": ["crowdstrike"],
    "EDR/XDR": ["edr", "xdr"],
    "Zero Trust": ["zero trust"],
    "MFA": ["mfa", "2fa", "autenticação multifator", "autenticacao multifator"],
    "SSO": ["sso", "single sign-on", "single sign on"],
    "SAML": ["saml"],
    "OpenID Connect": ["openid connect", "oidc"],
    "Keycloak": ["keycloak"],
    "Okta": ["okta"],
    "Auth0": ["auth0"],
    "TLS/SSL": ["tls", "ssl"],
    "WAF": ["waf"],
    "DLP": ["dlp"],
    "Threat Intelligence": ["threat intelligence", "inteligência de ameaças", "inteligencia de ameacas"],
    "Threat Hunting": ["threat hunting"],
    "Resposta a incidentes": ["incident response", "resposta a incidentes"],
    "Forense digital": ["forense digital", "digital forensics", "computação forense", "computacao forense"],
    "Análise de malware": ["malware analysis", "análise de malware", "analise de malware"],
    "Red Team": ["red team", "red teaming"],
    "Blue Team": ["blue team"],
    "GRC": ["grc"],
    "Gestão de riscos": ["gestão de riscos", "gestao de riscos", "risk management"],
    "Compliance": ["compliance", "conformidade"],
    "NIST": ["nist"],
    "ISO 27002": ["iso 27002"],
    "PCI DSS": ["pci dss", "pci-dss"],
    "SOC 2": ["soc 2", "soc2"],
    "GDPR": ["gdpr"],
    "CISSP": ["cissp"],
    "CEH": ["ceh"],
    "OSCP": ["oscp"],
    "Security+": ["security+", "comptia security+"],

    # --- Testes e qualidade (extras) ---
    "Vitest": ["vitest"],
    "Jasmine": ["jasmine"],
    "Testcontainers": ["testcontainers"],
    "Robolectric": ["robolectric"],
    "SpecFlow": ["specflow"],
    "Gherkin": ["gherkin"],
    "Page Object": ["page object", "page objects"],
    "TestComplete": ["testcomplete"],
    "Tricentis Tosca": ["tosca", "tricentis"],
    "UFT": ["uft"],
    "qTest": ["qtest"],
    "Charles Proxy": ["charles proxy"],
    "QA": ["qa", "quality assurance", "garantia de qualidade"],
    "Qualidade de software": ["qualidade de software", "software quality"],
    "Testes unitários": ["testes unitários", "testes unitarios", "teste unitário", "teste unitario", "unit testing", "unit tests", "unit test"],
    "Testes de integração": ["testes de integração", "testes de integracao", "teste de integração", "teste de integracao", "integration testing", "integration tests"],
    "Testes E2E": ["e2e", "end-to-end", "end to end"],
    "Testes de aceitação": ["testes de aceitação", "teste de aceitação", "testes de aceitacao", "teste de aceitacao", "uat"],
    "Testes de usabilidade": ["testes de usabilidade", "teste de usabilidade", "usability testing"],
    "Testes de contrato": ["testes de contrato", "teste de contrato", "contract testing"],
    "Smoke test": ["smoke test", "smoke tests", "teste de fumaça", "teste de fumaca"],
    "Casos de teste": ["casos de teste", "caso de teste", "test cases", "test case", "plano de testes", "test plan"],
    "Shift-left": ["shift left", "shift-left"],
    "Chaos Engineering": ["chaos engineering", "engenharia do caos"],

    # --- Arquitetura e práticas de engenharia (extras) ---
    "Event Sourcing": ["event sourcing"],
    "CQRS": ["cqrs"],
    "SOA": ["soa", "arquitetura orientada a serviços", "arquitetura orientada a servicos"],
    "BFF": ["bff", "backend for frontend"],
    "OpenAPI/Swagger": ["swagger", "openapi"],
    "Webhooks": ["webhook", "webhooks"],
    "Design de APIs": ["api design", "design de apis", "design de api"],
    "Escalabilidade": ["escalabilidade", "scalability"],
    "Alta disponibilidade": ["alta disponibilidade", "high availability"],
    "Cache": ["cache", "caching"],
    "System Design": ["system design", "design de sistemas"],
    "Refatoração": ["refatoração", "refatoracao", "refactoring"],
    "Pair programming": ["pair programming", "programação em par", "programacao em par"],
    "Feature Flags": ["feature flag", "feature flags", "feature toggle", "feature toggles"],
    "Trunk-based development": ["trunk-based", "trunk based"],
    "Programação funcional": ["programação funcional", "programacao funcional", "functional programming"],
    "Programação assíncrona": ["programação assíncrona", "programacao assincrona", "async/await", "asynchronous programming"],
    "Concorrência": ["concorrência", "concorrencia", "multithreading", "multi-threading", "programação concorrente", "programacao concorrente"],
    "Estruturas de dados": ["estruturas de dados", "data structures"],
    "Algoritmos": ["algoritmos", "algorithms"],
    "Lógica de programação": ["lógica de programação", "logica de programacao"],
    "Debugging": ["debugging", "depuração", "depuracao"],
    "Documentação técnica": ["documentação técnica", "documentacao tecnica", "technical documentation"],

    # --- ERP, low-code, automação e pagamentos ---
    "SAP": ["sap", "sap hana", "s/4hana"],
    "Salesforce": ["salesforce"],
    "Totvs": ["totvs", "protheus"],
    "Dynamics 365": ["dynamics 365", "dynamics crm"],
    "ServiceNow": ["servicenow"],
    "SharePoint": ["sharepoint"],
    "Microsoft 365": ["microsoft 365", "office 365", "m365"],
    "RPA": ["rpa", "robotic process automation"],
    "UiPath": ["uipath"],
    "n8n": ["n8n"],
    "Zapier": ["zapier"],
    "Low-code": ["low-code", "low code", "no-code", "no code"],
    "OutSystems": ["outsystems"],
    "Mendix": ["mendix"],
    "Pix": ["pix"],
    "Open Finance": ["open finance", "open banking"],
    "Stripe": ["stripe"],
    "Meios de pagamento": ["meios de pagamento", "gateway de pagamento", "payment gateway"],
    "Antifraude": ["antifraude", "fraud detection", "prevenção a fraudes", "prevencao a fraudes"],
    "ISO 8583": ["iso 8583"],

    # --- Embarcados, robótica, IoT e Web3 (extras) ---
    "FreeRTOS": ["freertos"],
    "RTOS": ["rtos"],
    "ESP32": ["esp32"],
    "STM32": ["stm32"],
    "FPGA": ["fpga"],
    "Yocto": ["yocto"],
    "CAN bus": ["can bus", "canbus"],
    "SCADA": ["scada"],
    "PLC": ["plc"],
    "ROS": ["ros2", "ros 2", "robot operating system"],
    "Robótica": ["robótica", "robotica", "robotics"],
    "Realidade aumentada/virtual": ["realidade aumentada", "realidade virtual", "augmented reality", "virtual reality"],
    "Hyperledger": ["hyperledger"],
    "NFT": ["nft", "nfts"],
    "DeFi": ["defi"],
    "Hardhat": ["hardhat"],

    # --- Gestão, produto e metodologia (extras) ---
    "SAFe": ["scaled agile", "scaled agile framework"],
    "Lean Startup": ["lean startup"],
    "Extreme Programming": ["extreme programming"],
    "Waterfall": ["waterfall", "modelo cascata"],
    "OKR": ["okr", "okrs"],
    "KPI": ["kpi", "kpis"],
    "SLA/SLO": ["sla", "slas", "slo", "slos"],
    "ITIL": ["itil"],
    "COBIT": ["cobit"],
    "PMP/PMBOK": ["pmp", "pmbok"],
    "Gestão de projetos": ["gestão de projetos", "gestao de projetos", "gerenciamento de projetos", "project management"],
    "Product Management": ["product management", "gestão de produto", "gestao de produto", "gerenciamento de produto"],
    "Product Owner": ["product owner"],
    "Scrum Master": ["scrum master"],
    "Roadmap": ["roadmap"],
    "Backlog": ["backlog"],
    "User Stories": ["user stories", "user story", "histórias de usuário", "historias de usuario"],
    "Critérios de aceite": ["critérios de aceite", "criterios de aceite", "acceptance criteria"],
    "Product Discovery": ["product discovery"],
    "Levantamento de requisitos": ["levantamento de requisitos", "análise de requisitos", "analise de requisitos", "engenharia de requisitos", "requirements gathering"],
    "BPMN": ["bpmn"],
    "Mapeamento de processos": ["mapeamento de processos", "modelagem de processos", "process mapping"],
    "Six Sigma": ["six sigma", "lean six sigma"],
    "SDLC": ["sdlc"],
    "Microsoft Teams": ["microsoft teams", "ms teams"],
    "Asana": ["asana"],
    "ClickUp": ["clickup"],
    "Azure Boards": ["azure boards"],
    "Redmine": ["redmine"],

    # --- Idiomas (extras) ---
    "Alemão": ["alemão", "alemao", "german"],
    "Francês": ["francês", "french"],
    "Italiano": ["italiano", "italian"],
    "Inglês": ["inglês", "ingles", "english"],
    "Espanhol": ["espanhol", "spanish"],
}

SOFT = {
    "Comunicação": ["comunicação", "comunicacao", "communication", "comunicativo", "comunicativa"],
    "Trabalho em equipe": ["trabalho em equipe", "trabalhar em equipe", "trabalho em time", "teamwork", "team work", "team player", "work in a team"],
    "Colaboração": ["colaboração", "colaboracao", "colaborativo", "colaborativa", "collaboration"],
    "Proatividade": ["proatividade", "proativo", "proativa", "proactive", "iniciativa", "initiative"],
    "Organização": ["organização", "organizacao", "organizado", "organizada"],
    "Resolução de problemas": ["resolução de problemas", "resolucao de problemas", "solução de problemas", "solucao de problemas", "resolver problemas", "problem solving", "problem-solving"],
    "Pensamento analítico": ["pensamento analítico", "pensamento analitico", "visão analítica", "analytical"],
    "Pensamento crítico": ["pensamento crítico", "pensamento critico", "critical thinking", "senso crítico"],
    "Liderança": ["liderança", "lideranca", "leadership"],
    "Mentoria": ["mentoria", "mentoring", "mentorship"],
    "Autonomia": ["autonomia", "autônomo", "autonomo", "autonomous"],
    "Adaptabilidade": ["adaptabilidade", "adaptability", "flexibilidade"],
    "Aprendizado contínuo": ["aprendizado contínuo", "aprendizado continuo", "vontade de aprender", "aprender rápido", "continuous learning"],
    "Atenção aos detalhes": ["atenção aos detalhes", "atencao aos detalhes", "atenção a detalhes", "senso de detalhe", "detail-oriented", "detail oriented"],
    "Criatividade": ["criatividade", "creativity"],
    "Curiosidade": ["curiosidade", "curiosity"],
    "Empatia": ["empatia", "empathy"],
    "Resiliência": ["resiliência", "resiliencia", "resilience"],
    "Responsabilidade": ["responsabilidade", "comprometimento", "senso de dono", "ownership"],
    "Gestão de tempo": ["gestão de tempo", "gestao de tempo", "gerenciamento de tempo", "time management"],
    "Foco em resultados": ["foco em resultados", "orientado a resultados", "orientação a resultados", "results-oriented"],
    "Visão de negócio": ["visão de negócio", "visão de negócios", "visao de negocio", "business acumen"],
    "Negociação": ["negociação", "negociacao", "negotiation"],
    "Relacionamento interpessoal": ["relacionamento interpessoal", "interpersonal"],
    "Gestão de conflitos": ["gestão de conflitos", "gestao de conflitos", "resolução de conflitos", "resolucao de conflitos", "conflict resolution"],
    "Tomada de decisão": ["tomada de decisão", "tomada de decisao", "decision making", "decision-making"],
    "Pensamento estratégico": ["pensamento estratégico", "pensamento estrategico", "visão estratégica", "visao estrategica", "strategic thinking"],
    "Pensamento sistêmico": ["pensamento sistêmico", "pensamento sistemico", "visão sistêmica", "visao sistemica", "systems thinking"],
    "Raciocínio lógico": ["raciocínio lógico", "raciocinio logico", "pensamento lógico", "pensamento logico", "logical thinking"],
    "Orientação a dados": ["data-driven", "data driven", "orientado a dados", "orientado por dados", "orientação a dados", "orientacao a dados", "decisões baseadas em dados", "decisoes baseadas em dados"],
    "Orientação ao cliente": ["orientação ao cliente", "orientacao ao cliente", "foco no cliente", "centrado no cliente", "customer focus", "customer-centric", "customer obsession"],
    "Gestão de pessoas": ["gestão de pessoas", "gestao de pessoas", "gestão de equipes", "gestao de equipes", "gerenciamento de equipes", "people management"],
    "Gestão de stakeholders": ["gestão de stakeholders", "gestao de stakeholders", "stakeholders", "stakeholder management"],
    "Gestão de mudanças": ["gestão de mudanças", "gestao de mudancas", "change management"],
    "Feedback": ["feedback", "feedbacks"],
    "Escuta ativa": ["escuta ativa", "active listening"],
    "Oratória": ["oratória", "oratoria", "public speaking", "habilidade de apresentação", "habilidades de apresentação"],
    "Comunicação escrita": ["comunicação escrita", "comunicacao escrita", "written communication"],
    "Facilitação": ["facilitação", "facilitacao", "facilitation", "facilitar reuniões", "facilitar reunioes"],
    "Compartilhamento de conhecimento": ["compartilhamento de conhecimento", "compartilhar conhecimento", "disseminar conhecimento", "knowledge sharing"],
    "Inteligência emocional": ["inteligência emocional", "inteligencia emocional", "emotional intelligence"],
    "Senso de urgência": ["senso de urgência", "senso de urgencia", "sense of urgency"],
    "Priorização": ["priorização", "priorizacao", "priorizar", "prioritization", "prioritize"],
    "Multitarefa": ["multitarefa", "multitasking", "multi-tasking"],
    "Trabalho sob pressão": ["trabalho sob pressão", "trabalho sob pressao", "sob pressão", "sob pressao", "work under pressure"],
    "Persistência": ["persistência", "persistencia", "perseverança", "perseveranca", "persistent"],
    "Ética e integridade": ["ética", "etica", "integridade", "integrity"],
    "Humildade": ["humildade", "humility", "humble"],
    "Transparência": ["transparência", "transparencia", "transparency"],
    "Mentalidade de crescimento": ["growth mindset", "mentalidade de crescimento"],
    "Mente aberta": ["mente aberta", "open-minded", "open minded"],
    "Inovação": ["inovação", "inovacao", "innovation", "mentalidade inovadora"],
    "Empreendedorismo": ["empreendedorismo", "espírito empreendedor", "espirito empreendedor", "mentalidade empreendedora", "entrepreneurial"],
    "Autogestão": ["autogestão", "autogestao", "self-management", "automotivado", "automotivada", "self-motivated"],
    "Autodidatismo": ["autodidata", "autodidatismo", "self-taught", "self-starter"],
    "Espírito de equipe": ["espírito de equipe", "espirito de equipe", "espírito colaborativo", "espirito colaborativo"],
    "Diversidade e inclusão": ["diversidade e inclusão", "diversidade e inclusao", "diversity and inclusion", "diversity & inclusion"],
    "Paixão por tecnologia": ["paixão por tecnologia", "paixao por tecnologia", "apaixonado por tecnologia", "apaixonada por tecnologia", "passionate about technology"],
    "Senso de qualidade": ["senso de qualidade", "foco em qualidade", "compromisso com qualidade", "orientado a qualidade"],
    "Objetividade": ["objetividade", "capacidade de síntese", "capacidade de sintese"],
}


def _compilar(dic: dict[str, list[str]]) -> dict[str, re.Pattern]:
    out = {}
    for nome, variantes in dic.items():
        alt = "|".join(re.escape(v) for v in sorted(variantes, key=len, reverse=True))
        # evita casar dentro de outras palavras (ex.: "java" em "javascript")
        out[nome] = re.compile(rf"(?<![\w.+#]){'(?:' + alt + ')'}(?![\w+#])", re.IGNORECASE)
    return out


_TEC = _compilar(TECNOLOGIAS)
_SOFT = _compilar(SOFT)

_NIVEIS = [
    ("estagio", r"est[áa]gi|\bintern\b|trainee"),
    ("lead", r"\blead\b|\bl[íi]der\b|tech lead"),
    ("senior", r"s[êe]nior|\bsr\b"),
    ("pleno", r"\bpleno\b|\bpl\b|\bmid\b"),
    ("junior", r"j[úu]nior|\bjr\b"),
]


def _nivel(titulo: str, texto: str) -> str:
    for alvo in (titulo, texto):
        for nome, padrao in _NIVEIS:
            if re.search(padrao, alvo, re.IGNORECASE):
                return nome
    return "nao_informado"


def _anos(texto: str) -> int | None:
    m = re.search(r"(\d{1,2})\s*\+?\s*(?:anos|years?)\s+(?:de\s+|of\s+)?experi", texto, re.I) or re.search(
        r"experi[eê]ncia[^.\n]{0,40}?(\d{1,2})\s*\+?\s*(?:anos|years?)", texto, re.I
    )
    return int(m.group(1)) if m else None


# negação curta antes do termo ("não é necessário conhecer X", "sem experiência em X")
_NEG = re.compile(r"n[ãa]o\s+(?:\w+\s+){0,2}?(?:necess|obrigat|preciso|exig)|\bsem\b|dispens", re.I)
# a partir de um título de seção como "Diferenciais" ou "Desejável", tudo é opcional
_SECAO = re.compile(r"^\W*(diferenciais?|desej[áa]ve(?:l|is)|nice to have|b[ôo]nus|plus)\b", re.I | re.M)


def _achou(padrao: re.Pattern, texto: str) -> bool:
    return any(
        not _NEG.search(texto[max(0, m.start() - 40) : m.start()]) for m in padrao.finditer(texto)
    )


def extrair_dicionario(vaga: dict) -> dict:
    titulo, desc = vaga["titulo"], vaga["descricao"]
    texto = f"{titulo}\n{desc}"
    m = _SECAO.search(desc)
    obrig, desej = (desc[: m.start()], desc[m.start() :]) if m else (desc, "")
    obrig = f"{titulo}\n{obrig}"
    tec = [n for n, p in _TEC.items() if _achou(p, obrig)]
    return {
        "tecnologias": tec,
        "diferenciais": [n for n, p in _TEC.items() if n not in tec and _achou(p, desej)],
        "soft_skills": [n for n, p in _SOFT.items() if _achou(p, texto)],
        "nivel": _nivel(titulo, texto),
        "anos_experiencia_min": _anos(texto),
    }